import {StyleSheet} from 'react-native';
import {vh, vw} from '../../Constants/Dimension';
export const styles = StyleSheet.create({
  parent: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: vh(89),
  },
  oldpassword: {
    height: vh(45),
    width: vw(315),
    borderRadius: vw(10),
    backgroundColor: '#f5f5f5',
    padding: vw(10),
  },
  input2: {
    flexDirection: 'row',
    backgroundColor: '#f5f5f5',
    alignItems: 'center',
    height: vh(45),
    width: vw(315),
    marginTop: vh(20),
    borderRadius: vw(10),
  },
  newpassword: {
    height: vh(45),
    width: vw(290),
    borderRadius: vw(10),
    backgroundColor: '#f5f5f5',
    padding: vw(10),
  },
  eye: {
    height: vw(11),
    width: vw(20),
  },
  Buttonupdate: {
    height: vh(45),
    width: vw(315),
    backgroundColor: '#ff9803',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: vw(10),
    marginTop: vh(25),
  },
  updatestyle: {
    color: '#ffffff',
    fontSize: vw(15),
  },
  privacytext: {
    fontSize: vw(15),
    color: '#ff9803',
    fontWeight: 'bold',
    marginLeft: vw(12),
    marginTop: vh(106),
  },
  middleview: {
    marginLeft: vw(15),
    marginTop: vh(15),
  },
  accounttext: {
    fontSize: vw(12),
    color: 'black',
    fontWeight: 'bold',
  },
  firsttext: {
    width: vw(339),
  },
  middletext: {
    fontSize: vw(12),
    color: '#A4A4A4',
  },
  Contenttext: {
    fontSize: vw(12),
    color: 'black',
    fontWeight: 'bold',
    marginTop: vh(15),
  },
  secondtextview: {
    width: vw(343),
  },
  parent2: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: vh(110),
  },
  name: {
    height: vh(45),
    width: vw(315),
    borderRadius: vw(10),
    backgroundColor: '#f5f5f5',
    padding: vw(10),
  },
  email: {
    height: vh(45),
    width: vw(315),
    borderRadius: vw(10),
    backgroundColor: '#f5f5f5',
    padding: vw(10),
    marginTop: vh(15),
  },
  title: {
    height: vh(45),
    width: vw(315),
    borderRadius: vw(10),
    backgroundColor: '#f5f5f5',
    padding: vw(10),
    marginTop: vh(15),
  },
  description: {
    height: vh(90),
    width: vw(315),
    borderRadius: vw(10),
    backgroundColor: '#f5f5f5',
    marginTop: vh(15),
    paddingLeft: vw(15),
    paddingTop: vh(17),
  },
  Buttonsubmit: {
    height: vh(45),
    width: vw(315),
    backgroundColor: '#ff9803',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: vw(10),
    marginTop: vh(25),
  },
  submitstyle: {
    color: '#ffffff',
    fontSize: vw(15),
    fontWeight: '600',
  },
  header: {
    height: vh(64),
    width: vw(375),
    marginTop: vh(48),
    backgroundColor: '#ff9803',
  },
  textsettings: {
    fontSize: vw(17),
    color: 'white',
    alignSelf: 'center',
    marginTop: vh(30),
    width: vw(63),
  },
  firstview: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginLeft: vw(15),
    marginTop: vh(17),
  },
  changeview: {
    flexDirection: 'row',
  },
  commonview: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginLeft: vw(15),
    marginTop: vh(25),
  },
  image: {
    width: vw(35),
    height: vw(35),
  },
  textchallenge: {
    fontSize: vw(12),
    alignSelf: 'center',
    marginLeft: vw(15),
    width: vw(252),
  },
  textupload: {
    fontSize: vw(12),
    alignSelf: 'center',
    marginLeft: vw(15),
    width: vw(261),
  },
  textipsum: {
    fontSize: vw(12),
    alignSelf: 'center',
    marginLeft: vw(15),
    width: vw(270),
  },
  imgarrow: {
    width: vw(8),
    height: vw(14),
    alignSelf: 'center',
    marginRight: vw(15),
    marginTop:vh(10)
  },
  imgtoggle: {
    width: vw(51),
    height: vw(31),
    borderRadius: vw(15),
    alignSelf: 'center',
    marginRight: vw(15),
  },
  termstext: {
    fontSize: vw(15),
    color: '#ff9803',
    fontWeight: 'bold',
    marginLeft: vw(15),
    marginTop: vh(85),
  },
  middle: {
    marginTop: vh(15),
    marginLeft: vw(15),
  },
  usertext: {
    fontSize: vw(12),
    color: 'black',
    fontWeight: 'bold',
  },
  middletextLorem: {
    fontSize: vw(12),
    color: '#A4A4A4',
    width: vw(344),
    marginTop: vh(13),
  },
  Content: {
    fontSize: vw(12),
    color: 'black',
    fontWeight: 'bold',
    marginTop: vh(18),
  },
  secondtext: {
    width: vw(332.5),
    height: vh(57.5),
    marginTop: vh(10),
  },
  middletextnext: {
    fontSize: vw(12),
    color: '#A4A4A4',
  },
  condtext: {
    fontSize: vw(15),
    color: '#ff9803',
    fontWeight: 'bold',
    marginTop: vh(40),
    marginLeft: vw(13),
  },
  lasttext: {
    marginTop: vh(15),
    paddingHorizontal: vw(15),
    fontSize: vw(12),
    color: '#A4A4A4',
  },
  parent1: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: vh(80),
  },
  first: {
    width: vw(345),
    borderRadius: vw(10),
    shadowOpacity: 0.3,
    shadowOffset: {height: vh(5), width: vw(2)},
    shadowColor: 'gray',
    backgroundColor: 'white',
    alignItems: 'center',
  },
  whenview: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#fff0d9',
    borderTopLeftRadius: vw(10),
    borderTopRightRadius: vw(10),
    width: vw(345),
    alignItems: 'center',
    paddingRight: vw(10),
  },
  whentext: {
    fontSize: vw(12),
    width: vw(267),
    marginLeft: vw(10),
    marginTop: vh(10),
    marginBottom: vh(10),
  },
  crossimg: {
    width: vw(15),
    height: vh(15),
    marginTop: vh(10),
    marginRight: vw(12),
  },
  Loremview: {
    width: vw(305),
    marginTop: vh(10),
  },
  Loremtext: {
    fontSize: vw(12.5),
    color: '#A4A4A4',
    marginVertical: vh(15),
  },
  common: {
    width: vw(345),
    borderRadius: vw(10),
    backgroundColor: '#fff0d9',
    marginTop: vh(20),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: vh(15),
  },
  textExc: {
    fontSize: vw(12),
    marginLeft: vw(10),
    marginTop: vh(10),
    width: vw(269),
  },
  addimg: {
    width: vw(19),
    height: vh(19),
    marginTop: vh(10),
    marginRight: vw(30),
    alignSelf: 'center',
  },
  notifytext: {
    fontSize: vw(15),
    alignSelf: 'center',
    marginLeft: vw(10),
  },
});
