const Images = {
    // SPLASH_IMG: require('../Assets/bg.jpeg'),
    ICWHITEBASE: require('../Assets/Images/icWhiteBase3x.png'),
    DOLLAR: require('../Assets/Images/icDollar2x.png'),
    GOLDMEDAL: require('../Assets/Images/goldMedal.png'),
    RULESICON: require('../Assets/Images/rulesicon.png'),
    CHECKMARK: require('../Assets/Images/checkMark.png'),
    BACKBUTTON: require('../Assets/Images/backButton.png'),
    WHITEBACKIMAGE: require('../Assets/Images/whiteBackImage.png'),
    DESCRIPTIONICON: require('../Assets/Images/descriptionicon.png'),
    CLOCK: require('../Assets/Images/clock.png'),
    PLUS: require('../Assets/Images/icPlus.png'),
    FOLLOWINGCHECK: require('../Assets/Images/icFollowingCheck.png'),
    TRANSCAMERA: require('../Assets/Images/icCameraTrans.png'),
    CLOSEWHITE: require('../Assets/Images/icCloseWhite.png'),
    APPICON: require('../Assets/Images/appIcon.png'),
    SPLASHBACKGROUND: require('../Assets/Images/bottomGraphic.png'),
    EDITIMAGE: require('../Assets/Images/icEditProfile.png'),
    GRIDFOCUSED: require('../Assets/Images/icGridFocused.png'),
    GRID: require('../Assets/Images/icGrid.png'),
    LISTIMAGE: require('../Assets/Images/icListView.png'),
    LISTFOCUSED: require('../Assets/Images/icList.png'),
    PROFILEPIC: require('../Assets/Images/icPofPic.png'),
    UNSELECTEDB: require('../Assets/Images/icUnselectedB.png'),
    UNSELECTEDCLAP: require('../Assets/Images/icUnselectedClap.png'),
    REPORT: require('../Assets/Images/icReport.png'),
    SHARE: require('../Assets/Images/icShare.png'),
    PLACEHOLDERIMAGE: require('../Assets/Images/icPlacHolderDetail.png'),
    HOME: require('../Assets/Images/icHomeSelected.png'),
    SETTINGS: require('../Assets/Images/icSettingsSelected.png'),
    NOTIFICATION: require('../Assets/Images/icNotificationSelected.png'),
    PROFILE: require('../Assets/Images/icProfileSelected.png'),
    SEARCH: require('../Assets/Images/icSearchSelected.png'),
    UNHOME: require('../Assets/Images/icHomeUnselected.png'),
    UNSETTINGS: require('../Assets/Images/icSettingsUnselected.png'),
    UNNOTIFICATION: require('../Assets/Images/icNotificationUnselected.png'),
    UNPROFILE: require('../Assets/Images/icProfileUnselected.png'),
    UNSEARCH: require('../Assets/Images/icSearchUnselected.png'),
    BRONZEMEDAL: require('../Assets/Images/icBronzeMedal.png'),
    SILVERMEDAL: require('../Assets/Images/icSilverMedal.png'),
    GOLDMEDAL: require('../Assets/Images/icGoldMedal.png'),
    LOGOORANGE: require('../Assets/Images/icLogoOrange.png'),
    INSTAGRAM: require('../Assets/Images/icInstagram.png'),
    FACEBOOK: require('../Assets/Images/icFb.png'),
    EYEACTIVE: require('../Assets/Images/icEyeActive.png'),
    EYEINACTIVE: require('../Assets/Images/icEyeInactive.png'),
    VALID: require('../Assets/Images/icValid.png'),
    INVALID: require('../Assets/Images/icInvalid.png'),
    SUCCESSGRAPHIC: require('../Assets/Images/icSuccessGraphic.png'),
    WON:require('../Assets/Images/icYouWon.png'),
    TOPGRAPHIC:require('../Assets/Images/icTopGraphic.png'),
    TROPHY:require('../Assets/Images/icTrophy.png'),
    DECORATION:require('../Assets/Images/icDecoration.png'),
    VOTESFINISHED:require('../Assets/Images/icGraphicVotesFinished.png')
    

}

export default Images;
