const Strings = {
    hello: "Hello",
    heading1: "\Manny Dolores\ voted for your photo in “Beach Happy”challenge.",
    heading2: "New challenge \“Roads less travelled”\ added in upcoming challenges.",
    heading3: "\Peter Caullins\ started following you",
    heading4: "\Peter Caullins\ voted for your photo in “Beach Happy”challenge",
    heading5: "Challnge \“7 Wonders of world”\  now active in current challenges.",
    time1ForNotification: "2m ago",
    time2ForNotification: "15m ago",
    time3ForNotification: "2h ago",
    time4ForNotification: "2h ago",
    time5ForNotification: "10h ago",
    search1:"Samuel Mathers",
    search2:"Damiam Evra",
    text1:"Terms & Conditions",
    text2:"FAQ's",
    text3:"About Us",
    text4:"Help & Support ",
    text5:"Invite Contact",
    text6:"Notification",
    text7:"Clear Search History",
    text8:"Deactivae Account",
    text9:"Sign Out",
    question1:"When does a new challenge start and how can I know?",
    question2:"How will I know I have won the challenge and how will I get the prize money?",
    question3:"How do I upload a picture in any challenge and what are the basic rules of submissions?",
    question4:"Lorem ipsum dolor sit amet, consectetur piscing elit, sed do eiusmod tempor?",
    question5:"Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt molli?",
    innertext:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Morbi quis commodo odio aenean sed adipiscing diam donec.Vulputate odio ut enim blandit volutpat enas volutpat. Quisque egestas diam in arcu.Cursus euismod quis viverra. Fames ac turpis egestas maecenas pharetra convallis posuere morbi. Consequat interdum varius sit amet mattis vulputate. Vel facilisis volutpat est velit egestas dui id. Purus non enim praesent elementum facilisis leo vel.Sed felis eget velit aliquet.Posuere lorem ipsum dolor sit amet consectetur adipiscing elit duis. Vitae semper quis lectus nulla. Consequat id porta nibh venenatis cras sed felis. Sed pulvinar proin gravida hendrerit lectus a. Turpis egestas maecenas pharetra convallis. "
}

export default Strings;